### ISSUE TITLE
The server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by hongbo-miao** [CodeSequence/ngrx-store-router#10]
The demo is not working
http://plnkr.co/edit/Gvg9fW?p=preview

It shows this error in the console:

> the server responded with a status of 400 (Bad Request)

**Comment by brandonroberts** [comment]
Thanks for the notice. I locked the plunker to version `0.2.0` since its using the deprecated router.

**Comment by hongbo-miao** [comment]
Cool! Now it works perfect!
