### ISSUE TITLE
The demo stops working

### ISSUE THREAD

**Issue by hongbo-miao** [CodeSequence/ngrx-store-router#12]
http://plnkr.co/edit/Gvg9fW?p=preview

It shows the error in the console:

> Failed to load resource: the server responded with a status of 404 ()
> 
> Error: Error loading https://npmcdn.com/@ngrx/store/store-backend.js as "@ngrx/store/store-backend" from https://npmcdn.com/@ngrx/devtools/dist/store/devtools.js

**Comment by brandonroberts** [comment]
Fixed via https://github.com/CodeSequence/ngrx-store-router/pull/13

**Comment by hongbo-miao** [comment]
Thanks!!
