### ISSUE TITLE
Doesn't work with AoT compiler

### ISSUE THREAD

**Issue by isaacplmann** [CodeSequence/ngrx-store-router#15]
The `provideRouterConnector()` function trips up the AoT compiler.

```
Error: Error encountered resolving symbol values statically. Calling function 'provideRouterConnector', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
```

Should people switch to using [@ngrx/router-store](https://github.com/ngrx/router-store) instead?

**Comment by brandonroberts** [comment]
Yes. I'll also fix this library to be compatible with AoT for those who are still using it.

**Comment by isaacplmann** [comment]
Thanks for the quick response.  FWIW, @ngrx/router-store was an easy drop-in replacement.

**Comment by brandonroberts** [comment]
Cool. Since I actively maintain that project, I'll update the readme to point there instead
