### ISSUE TITLE
wishlist/thoughts

### ISSUE THREAD

**Issue by laurelnaiad** [CodeSequence/ngrx-store-router#2]
#### sync

When a NAVIGATED action is reverted, what typically seems to happen is that the browser's url is set back to the value it had been previously (that's good!)... but it also triggers a new NAVIGATED entry (I don't think that's as good).

There's not a distinction being made between the forms (and instigators) of navigation.

[react-router-redux's sync module](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js) describes its logic as:

`* history.push -> store.dispatch -> enhancedHistory.listen -> router`

Do we have sufficient notifications and control over ng2 location and router to implement this strategy? Do we want to?
#### NAVIGATING action

Likewise, do we also have sufficient hooks from ng2 to implement NAVIGATING (such that it could be CANCELED by the app)?) 

It looks to me like there may be gaps that could be filled for now by _overwriting_ some of the ng2 methods, or maybe I'm missing the "right way" here.
#### equivalent (or improvement over) of RouterLink*

... and potentially other integrations
#### big picture question

Should this router be an _alternative_ to ng2 Router? 

Given that it seems there is a lot of angst in the community over certain present ng2 router issues, this may not be the best time to answer any of these questions, but just wanted to throw this up here.

**Comment by brandonroberts** [comment]
**sync**

I believe this was a bug in the way I was determining the initial router URL. The actions are being dispatched after the router emits the URL after navigation completes. We do have some control over ng2 location and the router will respond to location changes, but ultimately it ends with the URL being emitted.

**NAVIGATING action**

Outside of overwriting some of the ng2 router methods, cancelling navigation isn't straightforward. I would like to avoid doing this initially, but am open to looking at it in the future if not implemented natively in the router.

**RouterLink**

There is something that could be had here. In theory, we could push URLs to the store from a custom router link, a navigation action or some other means and it would trigger the router to navigate.

**big picture**

This isn't supposed to an alternative to ng2 router. Its main goal is to keep the router URL in sync with the store. I would like to have this same functionality in the ngrx router also, with possibly deeper integration as far as being able to replay each individual route being rendered, but that's still a work in progress.

**Comment by laurelnaiad** [comment]
Thanks for your replies.
